title_id: 12345
title: imp config settings
date: 2019-06-08T19:22:36.7619816-06:00
states: 1
sampling_frame: 1000
output_dir: c:\tmp\
data_directory: C:/tmp/
topology_file: Topology.txt
target_gmm_file: emd_1883.map.mrc.gmm.50.txt
crosslinkdb:
- refid: polii_xlinks.csv
- refid: polii_juri.csv
xl_groupA:
- refid: polii_xlinks.csv
  length: 21.0
  slope: 0.01
  resolution: 1.0
  label: Trnka
  weight: 1.0
  crosslink_distance: 10.834
- refid: polii_juri.csv
  length: 21.0
  slope: 0.01
  resolution: 1.0
  label: Chen
  weight: 1.0
  crosslink_distance: 10.834
xl_dbA:
- refid: polii_xlinks.csv
  set_protein1_key: pep1.accession
  set_protein2_key: pep2.accession
  set_residue1_key: pep1.xlinked_aa
  set_residue2_key: pep2.xlinked_aa
- refid: polii_juri.csv
  set_protein1_key: prot1
  set_protein2_key: prot2
  set_residue1_key: res1
  set_residue2_key: res2
degree_of_freedom:
  max_rb_trans: 4.0
  max_rb_rot: 0.3
  max_bead_trans: 4.0
  max_srb_trans: 4.0
  max_srb_rot: 0.3

